version: '3.0' # specify docker-compose version

# Define the services/containers to be run
services:
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
  angular: # name of the first service
    build: 
      context: ./PackageTracker # specify the directory of the Dockerfile
      dockerfile: DockerFile
    ports:
      - "4200:4200" # specify port forewarding

  express: #name of the second service
    build: 
      context: ./OrdertrackingAPI # specify the directory of the Dockerfile
      dockerfile: DockerFile
    ports:
      - "8000:8000" #specify ports forewarding
    links:
      - database # link this service to the database service


