FROM node:10
RUN mkdir -p /usr/src/app
WORKDIR  /usr/src/app
COPY package.json /usr/src/app
RUN npm cache clean
RUN npm install
COPY . /usr/src/app
EXPOSE 8000
CMD ["node","server.js", "dataScript.js"]